### ISSUE TITLE
Problems with Eclipse 2021-06 (4.20.0)

### ISSUE THREAD

**Issue by gepparta** [fidley/ABAPQuickFix#25]
Hi Łukasz, 

I'm not able to start quick Fixes via "CTRL+SHIFT+1" in ADT on Eclipse 2021-06 (4.20.0).
The popup just don't appear.

Is this a known bug you are working on?
 

KR
Alex

**Comment by fidley** [comment]
Hi Alex,
I saw this before and the issue was connection to bing translation services as far as I remember. Try disabling the translation quick fix in the settings and try again.

There should be also since entry in error log that could help me to find the issue. Would be great if you could paste it here.

I'll be back from holidays next week then I'll take a look on this.

Cheers
Łukasz

**Comment by gepparta** [comment]
Thanks Łukasz,

I have changed my preferences:

![image](https://user-images.githubusercontent.com/3863263/127637117-f685b0fa-4107-458e-b81c-9fe5d2b65b5d.png)


Now it is working again :-)

Kind regards
Alex

**Comment by fidley** [comment]
I'll reopen it as this might be an issue also for the others. What I will try to achieve is to add a check on the start of the Eclipse if there is a communication to the translation service. If not then I will omit calls to it during the quick fix if the preference to do translation was enabled. I may repeat the check once per 10-20 minutes for two-three times for those who connects via VPN.

**Comment by fidley** [comment]
After the corrections from #30, once the translation will fail to get an answer, it will not try again until next restart of eclipse
